# .github/workflows/app-tests.yml (Example 5-2)
name: Sample App Tests

on: push

jobs:
  sample_app_tests:
    name: "Run Tests Using Jest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 # Nouvelle action pour Node stable
        with:
          node-version: '18.x' # Utilisation de Node 18, très stable pour les dépendances
      - name: Install dependencies
        working-directory: td5/scripts/sample-app
        run: npm ci
      - name: Run tests
        working-directory: td5/scripts/sample-app
        run: npm test

